# coding: utf-8

"""
    cifrum API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.models_raw_values import ModelsRawValues  # noqa: E501
from swagger_client.rest import ApiException


class TestModelsRawValues(unittest.TestCase):
    """ModelsRawValues unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelsRawValues(self):
        """Test ModelsRawValues"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.models_raw_values.ModelsRawValues()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
