# coding: utf-8

"""
    cifrum API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.raw_values_api import RawValuesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRawValuesApi(unittest.TestCase):
    """RawValuesApi unit test stubs"""

    def setUp(self):
        self.api = api.raw_values_api.RawValuesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_raw_values(self):
        """Test case for raw_values

        Returns close values of a mutual fund by registrationNumber  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
