# coding: utf-8

"""
    cifrum API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.adjusted_values_api import AdjustedValuesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAdjustedValuesApi(unittest.TestCase):
    """AdjustedValuesApi unit test stubs"""

    def setUp(self):
        self.api = api.adjusted_values_api.AdjustedValuesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_adjusted_close_values(self):
        """Test case for adjusted_close_values

        Returns adjusted close values of a mutual fund by registrationNumber  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
