# coding: utf-8

"""
    cifrum API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.infos_api import InfosApi  # noqa: E501
from swagger_client.rest import ApiException


class TestInfosApi(unittest.TestCase):
    """InfosApi unit test stubs"""

    def setUp(self):
        self.api = api.infos_api.InfosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_mutru_info(self):
        """Test case for mutru_info

        Returns information of mutual fund by registrationNumber  # noqa: E501
        """
        pass

    def test_mutru_infos(self):
        """Test case for mutru_infos

        Returns all information of mutual funds  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
