# coding: utf-8

"""
    cifrum API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.routes_api import RoutesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRoutesApi(unittest.TestCase):
    """RoutesApi unit test stubs"""

    def setUp(self):
        self.api = api.routes_api.RoutesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_message(self):
        """Test case for message

        A sample message that returns current time  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
