# coding: utf-8

"""
    cifrum API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.models_mutual_fund_ru_info import ModelsMutualFundRuInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestModelsMutualFundRuInfo(unittest.TestCase):
    """ModelsMutualFundRuInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelsMutualFundRuInfo(self):
        """Test ModelsMutualFundRuInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.models_mutual_fund_ru_info.ModelsMutualFundRuInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
